# Generated by Django 5.0.6 on 2024-06-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_cities',
            field=models.TextField(blank=True),
        ),
    ]
